# Generated by Django 6.0.2 on 2026-03-27 20:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='smart_accounting/uploaded_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls'])], verbose_name='Original File')),
                ('original_file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('document_type', models.CharField(choices=[('invoice', 'Factura Electrónica'), ('receipt', 'Comprobante'), ('tax_document', 'Documento Fiscal'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedDocumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='No. Factura')),
                ('cufe', models.CharField(blank=True, max_length=100, verbose_name='CUFE')),
                ('issue_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Emisión')),
                ('issuer_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre Emisor')),
                ('issuer_ruc', models.CharField(blank=True, max_length=50, verbose_name='RUC Emisor')),
                ('issuer_dv', models.CharField(blank=True, max_length=10, verbose_name='DV Emisor')),
                ('receiver_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre Receptor')),
                ('receiver_ruc', models.CharField(blank=True, max_length=50, verbose_name='RUC Receptor')),
                ('receiver_dv', models.CharField(blank=True, max_length=10, verbose_name='DV Receptor')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ITBMS / Impuesto')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('raw_extracted_text', models.TextField(blank=True)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='mvp_smart_accounting.uploadeddocument')),
            ],
            options={
                'verbose_name': 'Parsed Document Data',
            },
        ),
        migrations.CreateModel(
            name='DocumentProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='mvp_smart_accounting.uploadeddocument')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
