# Generated by Django 6.0.2 on 2026-03-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_smart_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocumentdata',
            name='receiver_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Receptor'),
        ),
    ]
