# Generated by Django 6.0.2 on 2026-03-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_smart_accounting', '0002_parseddocumentdata_receiver_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddocumentdata',
            name='issuer_dv',
            field=models.CharField(blank=True, max_length=50, verbose_name='DV Emisor'),
        ),
        migrations.AlterField(
            model_name='parseddocumentdata',
            name='issuer_ruc',
            field=models.CharField(blank=True, max_length=255, verbose_name='RUC Emisor'),
        ),
        migrations.AlterField(
            model_name='parseddocumentdata',
            name='receiver_dv',
            field=models.CharField(blank=True, max_length=50, verbose_name='DV Receptor'),
        ),
        migrations.AlterField(
            model_name='parseddocumentdata',
            name='receiver_ruc',
            field=models.CharField(blank=True, max_length=255, verbose_name='RUC Receptor'),
        ),
    ]
