# Generated by Django 6.0.2 on 2026-04-02 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Branch Name')),
                ('slug', models.SlugField(help_text='Unique identifier for URL namespacing.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_digital_only', models.BooleanField(default=False, help_text='If True, disables physical thermal printing.')),
                ('auto_print', models.BooleanField(default=True, help_text='If True, attempts browser-based printing after ticket creation.')),
                ('requires_identification', models.BooleanField(default=False, help_text='If True, requests ID/DNI during ticket registration.')),
                ('has_priority_lane', models.BooleanField(default=True, help_text='If True, the branch supports priority handling.')),
                ('reset_policy', models.CharField(choices=[('never', 'Never Reset'), ('daily', 'Reset Daily')], default='daily', help_text='Controls whether ticket numbering resets daily.', max_length=20)),
                ('max_call_attempts', models.PositiveSmallIntegerField(default=3, help_text='Maximum number of call attempts before marking the ticket as missed.')),
                ('call_interval_seconds', models.PositiveIntegerField(default=20, help_text='Seconds to wait between call attempts.')),
                ('critical_wait_threshold_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before triggering a critical wait alert.')),
                ('enable_qr_tracking', models.BooleanField(default=True)),
                ('allow_customer_cancel', models.BooleanField(default=True)),
                ('show_estimated_wait_time', models.BooleanField(default=True)),
                ('public_message', models.CharField(blank=True, help_text='Main message shown in kiosk, public display, or ticket tracking pages.', max_length=255, null=True)),
                ('secondary_message', models.CharField(blank=True, help_text='Secondary helper message for customers.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Branch Setting',
                'verbose_name_plural': 'Branch Settings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Service Name')),
                ('slug', models.SlugField()),
                ('prefix', models.CharField(help_text='Example: A, B, PR, LAB', max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('use_branch_reset_policy', models.BooleanField(default=True, help_text='If True, uses the branch reset policy.')),
                ('reset_policy', models.CharField(choices=[('never', 'Never Reset'), ('daily', 'Reset Daily')], default='daily', help_text='Only applies when use_branch_reset_policy is False.', max_length=20)),
                ('average_service_time_minutes', models.PositiveIntegerField(default=8, help_text='Average service time used to estimate queue wait time.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mvp_qflow_core.branchsetting')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'ordering': ['branch__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('ticket_code', models.CharField(help_text='Human-readable ticket code like A-101.', max_length=30, unique=True)),
                ('internal_token', models.CharField(help_text='Unique collision-resistant token for QR and internal tracking.', max_length=80, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=30, null=True)),
                ('is_priority', models.BooleanField(default=False)),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=0)),
                ('people_ahead', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting in Queue'), ('called', 'Called to Counter'), ('attending', 'Currently Being Served'), ('finished', 'Service Completed'), ('missed', 'Customer Not Present'), ('cancelled', 'Cancelled by User/Staff')], default='waiting', max_length=20)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('service_start_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('missed_at', models.DateTimeField(blank=True, null=True)),
                ('call_attempts', models.PositiveSmallIntegerField(default=0)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qflow_attended_tickets', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='mvp_qflow_core.branchsetting')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='mvp_qflow_core.servicetype')),
            ],
            options={
                'verbose_name': 'Queue Ticket',
                'verbose_name_plural': 'Queue Tickets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical Failure')], default='info', max_length=10)),
                ('action', models.CharField(help_text="Description of the event, for example 'Ticket created' or 'Printing failure'.", max_length=255)),
                ('payload', models.JSONField(blank=True, help_text='Optional metadata or raw error details.', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qflow_processing_logs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='mvp_qflow_core.branchsetting')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='mvp_qflow_core.queueticket')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='mvp_qflow_core.servicetype')),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('result', models.CharField(choices=[('called', 'Ticket Called'), ('no_response', 'No Response'), ('answered', 'Customer Responded'), ('auto_missed', 'Marked as Missed Automatically')], default='called', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qflow_ticket_calls', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_events', to='mvp_qflow_core.queueticket')),
            ],
            options={
                'verbose_name': 'Ticket Call Event',
                'verbose_name_plural': 'Ticket Call Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_date', models.DateField(blank=True, help_text='Required when numbering resets daily.', null=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_sequences', to='mvp_qflow_core.branchsetting')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_sequences', to='mvp_qflow_core.servicetype')),
            ],
            options={
                'verbose_name': 'Ticket Sequence',
                'verbose_name_plural': 'Ticket Sequences',
            },
        ),
        migrations.AddConstraint(
            model_name='servicetype',
            constraint=models.UniqueConstraint(fields=('branch', 'slug'), name='unique_service_slug_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='servicetype',
            constraint=models.UniqueConstraint(fields=('branch', 'prefix'), name='unique_service_prefix_per_branch'),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['branch', 'service_type', 'status'], name='mvp_qflow_c_branch__5ed74e_idx'),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['status', 'created_at'], name='mvp_qflow_c_status_40e8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['ticket_code'], name='mvp_qflow_c_ticket__507185_idx'),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['internal_token'], name='mvp_qflow_c_interna_8edf2f_idx'),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['created_at'], name='mvp_qflow_c_created_f636e6_idx'),
        ),
        migrations.AddIndex(
            model_name='appprocessinglog',
            index=models.Index(fields=['level', 'created_at'], name='mvp_qflow_c_level_d77423_idx'),
        ),
        migrations.AddIndex(
            model_name='appprocessinglog',
            index=models.Index(fields=['branch', 'created_at'], name='mvp_qflow_c_branch__0cd278_idx'),
        ),
        migrations.AddIndex(
            model_name='appprocessinglog',
            index=models.Index(fields=['ticket', 'created_at'], name='mvp_qflow_c_ticket__c5e3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcall',
            index=models.Index(fields=['ticket', 'attempt_number'], name='mvp_qflow_c_ticket__6e2779_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcall',
            index=models.Index(fields=['result', 'created_at'], name='mvp_qflow_c_result_5124fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketsequence',
            constraint=models.UniqueConstraint(fields=('branch', 'service_type', 'sequence_date'), name='unique_ticket_sequence_scope'),
        ),
    ]
