# Generated by Django 6.0.2 on 2026-04-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_qflow_core', '0002_alter_ticketcall_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueticket',
            name='ticket_code',
            field=models.CharField(help_text='Human-readable ticket code like A-101.', max_length=30),
        ),
    ]
