# Generated by Django 6.0.2 on 2026-04-24 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Example: 'Main Brand - Instagram'", max_length=100)),
                ('source_type', models.CharField(choices=[('INSTAGRAM', 'Instagram Graph API'), ('GOOGLE_ANALYTICS', 'Google Analytics 4')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Connector Source',
                'verbose_name_plural': 'Connector Sources',
            },
        ),
        migrations.CreateModel(
            name='BigQueryTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255)),
                ('dataset_id', models.CharField(max_length=255)),
                ('table_id', models.CharField(max_length=255)),
                ('env_variable_name', models.CharField(default='GOOGLE_APPLICATION_CREDENTIALS', help_text='The name of the Environment Variable that holds the JSON Service Account key.', max_length=100)),
                ('connector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bq_destination', to='mvp_data_connectors.connectorsource')),
            ],
            options={
                'verbose_name': 'BigQuery Target',
                'verbose_name_plural': 'BigQuery Targets',
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('rows_affected', models.IntegerField(default=0)),
                ('log_details', models.TextField(blank=True, help_text='Logs, error messages, or API response summaries.', null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mvp_data_connectors.connectorsource')),
            ],
            options={
                'verbose_name': 'Execution Log',
                'verbose_name_plural': 'Execution Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="The parameter name (e.g., 'INSTAGRAM_APP_ID' or 'ENV_VAR_POINTER')", max_length=100)),
                ('value', models.TextField(help_text='The value or the name of the Environment Variable containing the secret.')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='mvp_data_connectors.connectorsource')),
            ],
            options={
                'verbose_name': 'Connector Credential',
                'unique_together': {('connector', 'key')},
            },
        ),
    ]
