# Generated by Django 6.0.2 on 2026-07-04 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Public title for the gift event or profile.', max_length=150)),
                ('owner_name', models.CharField(help_text='Name of the person who will receive the gifts.', max_length=120)),
                ('owner_email', models.EmailField(blank=True, help_text='Optional email address of the gift event owner.', max_length=254, null=True)),
                ('description', models.TextField(blank=True, help_text='Short description or message for guests.')),
                ('event_date', models.DateField(blank=True, help_text='Optional date for the celebration or event.', null=True)),
                ('token_url', models.CharField(editable=False, help_text='Unique public token used to access the shared gift profile.', max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether the public gift profile is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the gift event was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the gift event was last updated.')),
            ],
            options={
                'verbose_name': 'Gift Event',
                'verbose_name_plural': 'Gift Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or short description of the gift idea.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Additional details about the gift idea.')),
                ('product_url', models.URLField(blank=True, help_text='Optional external URL for a specific product.')),
                ('image', models.ImageField(blank=True, help_text='Optional uploaded image for the gift item.', null=True, upload_to='gifts/items/%Y/%m/')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional estimated price for the gift item.', max_digits=10, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level assigned by the gift event owner.', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('received', 'Received'), ('inactive', 'Inactive')], default='available', help_text='Current status of the gift item.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the gift item was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the gift item was last updated.')),
                ('gift_event', models.ForeignKey(help_text='Gift event associated with this gift item.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mvp_gifts.giftevent')),
            ],
            options={
                'verbose_name': 'Gift Item',
                'verbose_name_plural': 'Gift Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('likes', 'Likes'), ('dislikes', 'Dislikes'), ('sizes', 'Sizes'), ('colors', 'Colors'), ('brands', 'Brands'), ('interests', 'Interests'), ('avoid', 'Things to Avoid'), ('other', 'Other')], default='other', help_text='Type of preference being stored.', max_length=30)),
                ('title', models.CharField(help_text='Short label for the preference.', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Detailed preference information.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the preference was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the preference was last updated.')),
                ('gift_event', models.ForeignKey(help_text='Gift event associated with this preference.', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='mvp_gifts.giftevent')),
            ],
            options={
                'verbose_name': 'Gift Preference',
                'verbose_name_plural': 'Gift Preferences',
                'ordering': ['preference_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GiftReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, help_text='Optional name of the guest making the reservation.', max_length=120)),
                ('guest_email', models.EmailField(blank=True, help_text='Optional email of the guest making the reservation.', max_length=254)),
                ('message', models.TextField(blank=True, help_text='Optional private note from the guest.')),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the gift item was reserved.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether the reservation is currently active.')),
                ('gift_item', models.OneToOneField(help_text='Gift item reserved by the guest.', on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='mvp_gifts.giftitem')),
            ],
            options={
                'verbose_name': 'Gift Reservation',
                'verbose_name_plural': 'Gift Reservations',
                'ordering': ['-reserved_at'],
            },
        ),
    ]
