# Generated by Django 6.0.2 on 2026-07-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftevent',
            name='video',
            field=models.FileField(blank=True, help_text='Optional welcome video for guests (stored in media).', null=True, upload_to='gifts/events/videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='giftpreference',
            name='preference_type',
            field=models.CharField(choices=[('likes', 'Likes'), ('dislikes', 'Dislikes'), ('sizes', 'Sizes'), ('colors', 'Colors'), ('brands', 'Brands'), ('interests', 'Interests'), ('avoid', 'Things to Avoid'), ('other', 'Other')], default='likes', help_text='Type of preference being stored.', max_length=30),
        ),
    ]
