# Generated by Django 6.0.2 on 2026-07-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_gifts', '0002_giftevent_video_alter_giftpreference_preference_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(default='gifts', help_text="The code name identifier of the MVP project (e.g., 'gifts').", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'project_name')},
            },
        ),
    ]
